### ISSUE TITLE
reduce should also expect a function

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/js-advanced-functions-generalized-map-and-reduce-lab#2]
As written, `reduce` expects a function as one of its arguments, which is not mentioned in the readme.

**Comment by sgharms** [comment]
@PeteHanner 

Looking at the README, I see that we [specify a function as the second argument]( https://github.com/learn-co-curriculum/js-advanced-functions-generalized-map-and-reduce-lab/commit/d3d9c8539fa66196d33795453f124b9320bb4fee#diff-04c6e90faac2675aa89e2176d2eec7d8R192-R195) at line 192 of the README. Is there another place you were expecting to see it?

**Comment by PeteHanner** [comment]
I see that now, I was confused by line 206 since that's where I was referencing as I tried to build the function out.

**Comment by sgharms** [comment]
Any suggestions on what to change, if anything?

**Comment by sgharms** [comment]
@PeteHanner LMK if you have any specific changes (PRs always welcome!). I know you're busy doing the course, so I'll close this pending your availability ;)
